### PR TITLE
in this house we index at 0

### PR DESCRIPTION
**Pull request by joy-kitson**
Hey, I fixed your README. Just switched the filenames from ...-01 to ...-00

### CODE REVIEW

**Comment by tkitson** [comment]
Just gonna go ahead and do this...

**Comment by joy-kitson** [comment]
Oops, I kinda forgot how that works

**Comment by AlinaWithAFace** [comment]
have i told you lately how much i love you

**Comment by joy-kitson** [comment]
You have now, lol <3

On Sep 14, 2018 09:29, "Alina Christenbury" <notifications@github.com>
wrote:

Merged #1 <https://github.com/AlinaWithAFace/vip-vr/pull/1> into master.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/AlinaWithAFace/vip-vr/pull/1#event-1846112151>, or mute
the thread

**Pull request merged**
